version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rentwise-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rentwise-network

  nginx:
    image: nginx:alpine
    container_name: rentwise-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - rentwise-network

  db:
    image: mysql:8.0
    container_name: rentwise-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - rentwise-network

networks:
  rentwise-network:
    driver: bridge